name: Pull Request Tests

on:
  pull_request:

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run General Tests
        # See https://github.com/alleyinteractive/action-test-general for more options
        uses: alleyinteractive/action-test-general@develop

      - name: Run Node Tests
        # See https://github.com/alleyinteractive/action-test-node for more options
        uses: alleyinteractive/action-test-node@develop
        with:
          audit-skip: true
          test-skip: true

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install -q

      - name: Run PHP Tests
        run: |
          composer validate
          cp .env.example .env
          composer install --no-interaction --ignore-platform-reqs
          php artisan key:generate
          composer lint
          php artisan test
